### ISSUE TITLE
Error when trying to bind couchdb

### ISSUE THREAD

**Issue by SunnyLu1337** [arnaudsjs/YCSB-couchdb-binding#1]
I've added the folder YCSB-couchdb-binding to the YCSB folder and also made an entry in the pom.xml. When i'm starting ycsb and try to build the dependencies through maven (mvn clean package) i get the error, that the pom.xml of couchdb is missing:

[ERROR]   The project com.yahoo.ycsb:root:0.1.4 (/home/YCSB/pom.xml) has 1 error
[ERROR]     Child module /home/YCSB/couchdb/pom.xml of /home/YCSB/pom.xml does not exist

**Comment by arnaudsjs** [comment]
The pom.xml file is available in the master branch of the YCSB-couchdb-binding repository. Pull to the newest revision of this repository and run the "mvn clean package" command again to compile everything. Let me know in case further issues arise.

**Comment by SunnyLu1337** [comment]
it works now! :+1: thanks!!

**Comment by SunnyLu1337** [comment]
Ok, after the maven resolving package worked i got another issue. When i try to run YCSB with the command "/bin/ycsb load couchdb -P workloads/workloada" it says "ERROR: Database 'couchdb' not found" - so it can't find the interface but i dont know why? I've got that folder "couchdb" in the folder "YCSB" where your folder "YCSB-couchdb-binding-master", the "org.ektorp" and the pom.xml lies.

**Comment by korchix** [comment]
Hi Laphory, i compiled the Project with eclipse, i named it "couchdbclient.jar" , and run the following command:
/YCSB-master# java -cp core/target/core-0.1.4.jar:couchdbclient.jar com.yahoo.ycsb.Client -load -db couchDBTest.CouchdbClient -P workloads/workloada

couchDBTest = my package name in eclipse.
CouchdbClient = class name
and it works, you can try it

**Comment by korchix** [comment]
Hi arnaud123, can you help with this please, when i run the benchmar, couchdb is to slow in inserting the queries, the stderr look like this:
2014-12-12 20:28:39:352 0 sec: 0 operations; 
2014-12-12 20:28:49:384 10 sec: 4025 operations; 401.26 current ops/sec; [INSERT AverageLatency(us)=225421.72] 
2014-12-12 20:28:59:477 20 sec: 8700 operations; 463.15 current ops/sec; [INSERT AverageLatency(us)=215876.23] 
....
can you please tell me why the "current ops/sec" is so slow ? i used 100 threads for it.
MongoDb insert 12x fast the same queries. in mongodb it looks like this:
2014-12-12 19:39:15:577 10 sec: 126478 operations; 12645.27 current ops/sec; [INSERT AverageLatency(us)=7753.27] 
2014-12-12 19:39:35:581 20 sec: 225962 operations; 12655.93 current ops/sec; [INSERT AverageLatency(us)=9388.16] 
.....
thank you.

**Comment by SunnyLu1337** [comment]
@korchix: so you just created a package and put the interface layer CouchdbClient.java in it and exported it as couchdbclient.jar. Where did you put the couchdbclient.jar, i mean in which folder? In the YCSB/core/target folder?

thanks for your help!

**Comment by SunnyLu1337** [comment]
When i tried it like that i get the following error:
Command line: -load -db couchDBTest.CouchdbClient -P workloads/workloada
Loading workload...
Starting test.
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
    The declared package "couchdbBinding.java" does not match the expected package "couchDBTest"
The import org.ektorp cannot be resolved
The import org.json cannot be resolved
DB cannot be resolved to a type
CouchDbConnector cannot be resolved to a type
...
and so on

**Comment by korchix** [comment]
Hi laphory, i copied all the classes in the project of arnaud123, in a new project in eclipse named couchDBTest, but i keept the same name of the classes and the same code ofcourse . then you should try to resolve the dependeciese problemes that apears like importing the ektop jar file and others jar files untile the errors desapear, then export the project in a jar file , i named my exported jar file "couchdbclient.jar"
this file should be in the root directory of YCSB.
if some dependecies problems aprears while executing the workloads , you should copy the importet jar files, like ektorp ..etc that you importet in your eclipse project to the directory /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext
java-7-openjdk-amd64 = the openjdk java file version 7 
than it should works. 
the code i used to execute this binding is montioned in https://github.com/brianfrankcooper/YCSB/wiki/Adding-a-Database#step-6--use-it-with-the-ycsb-client

**Comment by SunnyLu1337** [comment]
Wow, thanks for the explanation! Can you maybe send me your .jar file on my mail? it is in my profile, i would appreciate it! thank you very much!

**Comment by arnaudsjs** [comment]
@korchix I need more information about you benchmark setup to answer your question.
- Do you use both databases in "standalone" modus or in cluster modus? (how many nodes?, how is data written to the cluster?)
- Mongodb supports different write conerns. By default mongodb writes asynchronous to disk which speeds up the performance, but might have data-loss in case of failure.  Couchdb has a similar setting called sync() => google it!
- Do both setups have the same amount of RAM available? More RAM allows more caching in memory which increases the performance significantly.

**Comment by korchix** [comment]
@arnaud123 i use the database in standalone modus.
- i installed couchdb and mongo db in my PC (ubuntu os) and i'm benchmarking the databases local , so no cluster just one pc
- both setups operating on the same PC , so the same Ram (8 GB) and the same Hard Disk (400 GB).
- for mongodb i user write.concern = safe . for couchdb i will google sync() and try it. thank you for the advice.
  i appreciate your Help a lot.

**Comment by SunnyLu1337** [comment]
Ok i'm back with my issue. Even with the command and the .jar from korchix it doesnt work. I'm wondering why it doesn't work with the normal way you also you mongodb. Like just with the command "./bin/ycsb load couchdb -P workloads/workloada"
Any other suggestions? :/

**Comment by arnaudsjs** [comment]
@laphory : I notices there are more dependency problem. I will fix them in the near future. To make it work quickly do the following: 
- clone the couchdb directory from the following repo: https://github.com/arnaud123/YCSB-1 into you YCSB project
- This should be enought to run the command: "./bin/ycsb load couchdb -P workloads/workloada"

Note: make sure that the line: <<"couchdb" : "couchdbBinding.java.CouchdbClient">> is defined in the DATABASES section of your bin/ycsb file.

**Comment by SunnyLu1337** [comment]
I copied the folder couchdb in my YCSB projekt and set the bin/ycsb file to: "couchdb"     : "couchdbBinding.java.CouchdbClient" and also tried it with "couchdb"    : "com.yahoo.ycsb.db.CouchdbClient".

When i now run the command i got following errors:
Loading workload...
Starting test.
Exception in thread "Thread-1" java.lang.NullPointerException
    at couchdbBinding.java.CouchdbClient.getUrlsForHosts(CouchdbClient.java:74)
    at couchdbBinding.java.CouchdbClient.init(CouchdbClient.java:101)
    at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
    at com.yahoo.ycsb.ClientThread.run(Client.java:197)
[OVERALL], RunTime(ms), 3.0
[OVERALL], Throughput(ops/sec), 0.0

Thanks for your help, really appreaciate it!

**Comment by arnaudsjs** [comment]
Pass this as a parameter: -p hosts="comma separated list of ips of you database nodes"

**Comment by SunnyLu1337** [comment]
still doesn't work :/ i only got 1 database with my localhost IP
command: "./bin/ycsb load couchdb -P workloads/workloada -p hosts="192.168.150.128" or
"./bin/ycsb load couchdb -P workloads/workloada -p hosts="localhost"

Error:
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: consistencyTests/util/StringToStringMap
    at couchdbBinding.java.CouchdbClient.insert(CouchdbClient.java:253)
    at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:148)
    at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:461)
    at com.yahoo.ycsb.ClientThread.run(Client.java:277)
Caused by: java.lang.ClassNotFoundException: consistencyTests.util.StringToStringMap
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 4 more
[OVERALL], RunTime(ms), 626.0
[OVERALL], Throughput(ops/sec), 0.0

**Comment by arnaudsjs** [comment]
Also add the util.jar from  https://github.com/arnaud123/YCSB-1 to your YCSB project. Sorry for the dependency issues.

**Comment by SunnyLu1337** [comment]
it works now! thank you so much!!

**Comment by SunnyLu1337** [comment]
Hello again arnaud!
I don't know if the issue i've got is produced by the interface layer but if i load the database mongodb with 1GB it takes much shorter than loading the couchdb database.

load phase with 1GB:

i use the following command for mongodb:
./bin/ycsb load mongodb -P workloads/workloada -p recordcount=10000 -p threads=100 -s > mongodbload_1gb.txt

output:
[OVERALL], RunTime(ms), 1652.0
[OVERALL], Throughput(ops/sec), 6053.268765133172
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 1357.0
[CLEANUP], MinLatency(us), 1357
[CLEANUP], MaxLatency(us), 1357
[CLEANUP], 95thPercentileLatency(ms), 1
[CLEANUP], 99thPercentileLatency(ms), 1

if i do it with couchdb it takes a lot of time and the difference is huge. Even in the transaction phase, there is the same issue.

the command  for couchdb:
/bin/ycsb load couchdb -P workloads/workloada -p recordcount=10000 -p threads=100 -p hosts="192.168.150.129" -s > couchdbload_1gb.txt

output:
[OVERALL], RunTime(ms), 450691.0
[OVERALL], Throughput(ops/sec), 22.18815108355836
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 5.0
[CLEANUP], MinLatency(us), 5
[CLEANUP], MaxLatency(us), 5
[CLEANUP], 95thPercentileLatency(ms), 0
[CLEANUP], 99thPercentileLatency(ms), 0

transaction phase on mongodb and couchdb:

command for mongodb:
./bin/ycsb run mongodb -P workloads/workloada -p operationcount=10000 -p threads=100 -p target=200 -s > mongodbrun_1gb_tag1.txt

output:
[OVERALL], RunTime(ms), 50133.0
[OVERALL], Throughput(ops/sec), 199.46941136576706
[READ], Operations, 5004
[READ], AverageLatency(us), 214.3870903277378
[READ], MinLatency(us), 64
[READ], MaxLatency(us), 5044
[READ], 95thPercentileLatency(ms), 0
[READ], 99thPercentileLatency(ms), 0
[READ], Return=0, 5004

./bin/ycsb run couchdb -P workloads/workloada -p operationcount=10000 -p threads=100 -p target=200 -p hosts="192.168.150.129" -s > couchdbrun_1gb_tag1.txt

output:
[OVERALL], RunTime(ms), 470433.0
[OVERALL], Throughput(ops/sec), 21.257012156885253
[READ], Operations, 5010
[READ], AverageLatency(us), 24648.990618762477
[READ], MinLatency(us), 1816
[READ], MaxLatency(us), 73234
[READ], 95thPercentileLatency(ms), 44
[READ], 99thPercentileLatency(ms), 44
[READ], Return=0, 5010

i found out that couchdb reaches always a throughput (op/sec) around (even in the load phase):
21.241705114152925

it never reaches the target 200 like mongodb

**Comment by arnaudsjs** [comment]
Do you always achieve the same throughput for CouchDB. Also when changing the amount of client threads?

**Comment by SunnyLu1337** [comment]
Sorry arnaud! I made a mistake, the command to set the client threads is "-threads 100", thats why YCSB never took 100 client threads. Nevertheless CouchDB gets always bad results in opposite to MongoDB or OrientDB, but i guess that's just the database. Thanks for your help

**Comment by arnaudsjs** [comment]
The maven dependency issue is fixed in the master branch now!

**Comment by AhmedSalahBasha** [comment]
I have a problem when binding couchdb alone
`mvn -pl com.yahoo.ycsb:couchdb-binding -am clean package`

this is the error:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YCSB Root .......................................... SUCCESS [  2.712 s]
[INFO] Core YCSB .......................................... SUCCESS [  8.582 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.423 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  0.985 s]
[INFO] CouchDB DB Binding ................................. FAILURE [  2.711 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.231 s
[INFO] Finished at: 2018-01-03T14:02:17+00:00
[INFO] Final Memory: 33M/79M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project couchdb-binding: You have 536 Checkstyle violations. -> [Help 1]

also, I read the above comments and tried to clone **couchdb** directory from this repo >> https://github.com/arnaud123/YCSB-1  and also include **util.jar**  as you said above! 
but still the same problem

**Comment by sathasivam95** [comment]
Hi @AhmedSalahBasha  did u manage to fix it? I am trying to get it work for YCSB-0.17.0. I'm having similar problems.

VirtualBox:~/ycsb-0.17.0$ bin/ycsb load couchdb -s -P workloads/workloada
java -cp /home/satha/ycsb-0.17.0/couchdb-binding/conf:/home/satha/ycsb-0.17.0/conf:/home/satha/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/home/satha/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/home/satha/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/home/satha/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/home/satha/ycsb-0.17.0/lib/core-0.17.0.jar:/home/satha/ycsb-0.17.0/couchdb-binding/lib/json-simple-1.1.1.jar:/home/satha/ycsb-0.17.0/couchdb-binding/lib/org.ektorp-1.5.0.jar:/home/satha/ycsb-0.17.0/couchdb-binding/lib/lightcouch-0.2.0.jar site.ycsb.Client -db site.ycsb.db.couchdb.CouchDBClient -s -P workloads/workloada -load
Command line: -db site.ycsb.db.couchdb.CouchDBClient -s -P workloads/workloada -load
YCSB Client 0.17.0

Loading workload...
Starting test.
java.lang.ClassNotFoundException: site.ycsb.db.couchdb.CouchDBClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at site.ycsb.DBFactory.newDB(DBFactory.java:38)
	at site.ycsb.Client.initDb(Client.java:428)
	at site.ycsb.Client.main(Client.java:311)
Exception in thread "Thread-2" java.lang.NullPointerException
	at site.ycsb.ClientThread.run(ClientThread.java:91)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-21 17:36:03:965 0 sec: 0 operations; est completion in 0 second 
2021-09-21 17:36:03:969 0 sec: 0 operations; est completion in 106751991167300 days 15 hours 
[OVERALL], RunTime(ms), 1
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_G1_Young_Generation], Count, 0
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.0
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0
satha@satha-VirtualBox:~/ycsb-0.17.0$
