### ISSUE TITLE
Update the project to work with  0.15

### ISSUE THREAD

**Issue by alinoil** [arnaudsjs/YCSB-couchdb-binding#7]
Could you update the project to work with YCSB 0.15?
I am trying to get it to work but running into problems with maven.

**Comment by LukaszPa** [comment]
i try to update it to 0.17 but i get error 
Non-resolvable parent POM for com.yahoo.ycsb:couchdb-binding:0.1.4: Failure to find com.yahoo.ycsb:root:pom:0.1.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 11 -> [Help 2]

can someone help ?
